# Deployment do Postgre
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres 
spec:
  selector:
    matchLabels:
      app: postgres 
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.3
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "1q2w3e4r5t"
            - name: POSTGRES_USER
              value: "luismartorano"
            - name: POSTGRES_DB
              value: "kubenews"

---
apiVersion: v1 
kind: Service 
metadata:
  name: postgres
spec:
  selector:
    app: postgres 
  ports: 
  - port: 5432 
    targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: kubenews
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
      - name: kubenews
        image: luismartorano/kubenewsv1:latest
        env:
        - name: DB_DATABASE
          value: "kubenews"
        - name: DB_USERNAME
          value: "luismartorano"
        - name: DB_PASSWORD
          value: "1q2w3e4r5t"
        - name: DB_HOST
          value: "postgres"

---
apiVersion: v1 
kind: Service
metadata:
  name: kube-news 
spec: 
  selector:
    app: kubenews
  ports: 
  - port: 80
    targetPort: 8080
    #nodePort: 30000
  type: NodePort