apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenewsv1
spec:
   replicas: 3
   selector:
     matchLabels:
       app: kubenewsv1
   template:
     metadata:
       labels:
         app: kubenewsv1
     spec:
       containers:
         - name: kubenewsv1
           image: luismartorano/kubenewsv1:latest
           ports:
             - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: kubenewsv1
spec: 
  selector: 
    app: kubenewsv1
  ports:
    - port: 9081
      targetPort: 8081
      protocol: TCP
      name: http
      #nodePort: 30000
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubenewsv1
  annotations:
    kubernetes.io/ingress.class: "nginx"

spec: 
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: kubenewsv1
            port:
              number: 8081
      
